### ISSUE TITLE
frontend: config is not defined

### ISSUE THREAD

**Issue by dannyvolkaerts** [conveyordata/data-product-portal#29]
## Describe the bug
![image](https://github.com/conveyordata/data-product-portal/assets/47820826/983f99c2-9abc-43f8-9cc8-d360d5cc32c4)

### Steps to reproduce
docker compose up runs perfectly

### Expected behavior
frontpage at port 8080

### Environment
Linux Ubuntu

### Additional context
When I visit the page 8080, there is nothing displayed although connection is established.
![image](https://github.com/conveyordata/data-product-portal/assets/47820826/af5dbbf0-02d9-4054-abc8-0766518c4ccc)

**Comment by stijn-janssens** [comment]
Hi Danny, could you please do some double checks for me so I can better understand the issue.
I can not reproduce the issue myself. 
- Are you executing docker compose in the root of the project? Or are you trying to start the frontend docker only?
- What do the logs of the frontend docker say, both while building as while running
- In /frontend, do you still have the config.docker.js file?
- This config.docker.js file is picked up in the compose.yaml as a volume on line 19, could you check that this volume is correctly mounted in the frontend docker?

Let me know if I can help further

**Comment by stijn-janssens** [comment]
Issue is related to port-forwarding / file serving from a different server to localhost when running docker compose.

**Comment by karim-soufi** [comment]
hello,
I am having the same issue. I am running docker compose locally.

**Comment by stijn-janssens** [comment]
Could you please share some more information, as explained above?

**Comment by karim-soufi** [comment]
- executing docker compose in the root of the project.
- file attached. [frontend_logs.txt](https://github.com/user-attachments/files/16230758/frontend_logs.txt)
- yes, config.docker.js is still there.

**Comment by Charles-deJager-NTT** [comment]
I can confirm that I am receiving the exact same error.

**Comment by stijn-janssens** [comment]
Hi all, trying to further debug this issue as I still can't reproduce it.
- Do you see any issues / errors during docker compose build time?
- On which platform are you running? Mac / linux or windows?
- Could you test if swapping out `${PWD}` for `.` on line 19 of `compose.yaml` solves the issue? (Rebuild using `docker compose up --build`
- Are you opening `localhost:8080` after the compose is up and running?

**Comment by karim-soufi** [comment]
hello @stijn-janssens 
shouldn't this issue be open ? 

Can you share the process through which you're running locally the docker compose? probably something is missing from the installation section.

I am running on windows. havent tested rebuilding yet.

**Comment by stijn-janssens** [comment]
I have discovered some issues with the docker compose file that might explain the problems you are having.
These issues have now been fixed. Do let me know if the issue is not solved on your end.

**Comment by karim-soufi** [comment]
it works. thank you @stijn-janssens
