### ISSUE TITLE
Move pytest fixtures to Factory Boy

### ISSUE THREAD

**Issue by stijn-janssens** [conveyordata/data-product-portal#43]
## Summary
The python library Factory Boy significantly improves the code experience when writing unit tests for ORM projects.

### Motivation
Currently we are writing fixtures for all of the database entries used in our unit tests.
This becomes unmanageable in the long run, or for complicated database entries.
Factory Boy improves this by creating factories for all of the entities. This allows creation of complex db entries in a very declarative way.
https://factoryboy.readthedocs.io/en/stable/introduction.html

**Comment by andrii-ivaniuk** [comment]
Factory Boy has been added to the codebase. All new tests should use Factory Boy instead of pytest fixtures.

All the existing tests will be migrated gradually.
