### ISSUE TITLE
Show through a visual indication that you are an admin in the UI

### ISSUE THREAD

**Issue by stijn-janssens** [conveyordata/data-product-portal#51]
## Summary
Show with some kind of icon / visual indication that you are an admin when you are visiting portal through the web UI

### Basic example
Icon with a tooltip next to your name might be sufficient.
Or some kind of border that clearly shows you are authorised to do everything

### Motivation
To make clear that you have elevated admin privileges and that that is the reason why you can access everything

**Comment by iamisam** [comment]
Hi @stijn-janssens , I am willing to work on this issue. Can you assign it to me ?

**Comment by stijn-janssens** [comment]
Looking forward to what you come up with! Have fun

**Comment by iamisam** [comment]
Hey @stijn-janssens I am trying to setup the project locally and have followed the instructions from the `README.md` file.
```
docker compose up
```
I get an error when I try to run 
```node
npm run dev
```

**Error Message**:
> data-product-portal-client@0.0.0 copy-config
> cp config.local.js public/config.js

Can you help me out here a bit as to what I should do ?

**Comment by stijn-janssens** [comment]
Hi @iamisam , have you followed the [setup instructions](https://github.com/conveyordata/data-product-portal/blob/main/frontend/README.md) for Frontend as well?
Based on your error I guess you did not create a `config.local.js` file. It is required to set some config fields.
Let me know if it works after you follow the readme!

**Comment by iamisam** [comment]
Hi @stijn-janssens , I am able to run the frontend through `npm run dev` but I get an error 
> Failed to load resource: net::ERR_CONNECTION_REFUSED

in `:5050/api/auth/user`. 

I am new to this and am failing to setup the project. Could you please help me out a bit ?

**Comment by stijn-janssens** [comment]
Failing calls to `:5050/api` indicate an issue with your local portal backend.

Make sure you are running a backend as well.
Either
- run the backend locally from the folder. See Readme in `/backend`
- run the backend with `docker compose up` in root.

There might be a slight misconfiguration (missing ALLOW_CORS) in the previous version of the `.env.docker` file, so I suggest you pull from `main` and do `docker compose up --build`

**Comment by iamisam** [comment]
Hey @stijn-janssens I think I will need to learn a lot of stuff before I can get into contributing to open source thanks for the opportunity.
